version: "3.3"
services:
  fpm:
    build: .
    container_name: fpm_container
    volumes:
      - ./:/var/web
    ports:
      - "9001:9000"
    depends_on:
      - mysqldb
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8888:80"
    command: /bin/sh -c "cp /var/web/nginx.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./:/var/web
    depends_on:
      - fpm
    networks:
      - app-network

  mysqldb:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_test
    ports:
      - "33061:3306"
    networks:
      - app-network
    volumes:
      - ./docker/mysql/mysql-data:/var/lib/mysql
      - ./docker/mysql/mysql-init-files:/docker-entrypoint-initdb.d

networks:
  app-network:
    driver: bridge